<?php

/**
 * Implementation of hook_views_api().
 */
function newsml_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'newsml') .'/views'
  );
}

/**
 * Implements hook_image_default_styles().
 */
function theweek_feeds_image_default_styles() {
  $styles = array();

  // Exported image style: theweek_msn_feed
  $styles['newsml_feed'] = array(
    'name' => 'newsml_feed',
    'effects' => array(
      1 => array(
        'label' => 'Scale and crop',
        'help' => 'Scale and crop will maintain the aspect-ratio of the original image, then crop the larger dimension. This is most useful for creating perfectly square thumbnails without stretching the image.',
        'effect callback' => 'image_scale_and_crop_effect',
        'dimensions callback' => 'image_resize_dimensions',
        'form callback' => 'image_resize_form',
        'summary theme' => 'image_resize_summary',
        'module' => 'image',
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => '300',
          'height' => '170',
        ),
        'weight' => '1',
      ),
    ),
  );

  return $styles;
}